"""empty message

Revision ID: 273539c1d42d
Revises: 5506116e67a2
Create Date: 2025-09-25 18:34:26.835555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273539c1d42d'
down_revision: Union[str, Sequence[str], None] = '5506116e67a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('call_purpose', sa.String(length=255), nullable=False))
    op.drop_column('calls', 'call_purpouse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('call_purpouse', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('calls', 'call_purpose')
    # ### end Alembic commands ###
