"""empty message

Revision ID: 49ea9f9859bc
Revises: 60a75ede5d66
Create Date: 2025-10-21 09:58:28.318925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ea9f9859bc'
down_revision: Union[str, Sequence[str], None] = '60a75ede5d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_calls_association_call_id_fkey'), 'users_calls_association', type_='foreignkey')
    op.drop_constraint(op.f('users_calls_association_user_id_fkey'), 'users_calls_association', type_='foreignkey')
    op.create_foreign_key(None, 'users_calls_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_calls_association', 'calls', ['call_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_calls_association', type_='foreignkey')
    op.drop_constraint(None, 'users_calls_association', type_='foreignkey')
    op.create_foreign_key(op.f('users_calls_association_user_id_fkey'), 'users_calls_association', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('users_calls_association_call_id_fkey'), 'users_calls_association', 'calls', ['call_id'], ['id'])
    # ### end Alembic commands ###
