"""empty message

Revision ID: 6114684d7545
Revises: 727cf130c2eb
Create Date: 2025-10-15 19:06:02.483844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6114684d7545'
down_revision: Union[str, Sequence[str], None] = '727cf130c2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('call_invoke_id', sa.String(), nullable=True))
    op.drop_column('calls', 'call_ivoke_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('call_ivoke_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('calls', 'call_invoke_id')
    # ### end Alembic commands ###
