"""empty message

Revision ID: 727cf130c2eb
Revises: 557e77bf3af6
Create Date: 2025-10-15 18:54:36.522667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727cf130c2eb'
down_revision: Union[str, Sequence[str], None] = '557e77bf3af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('call_ivoke_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'call_ivoke_id')
    # ### end Alembic commands ###
