"""empty message

Revision ID: 79a921a7acb3
Revises: fd91b2ece527
Create Date: 2025-10-16 18:21:25.886579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a921a7acb3'
down_revision: Union[str, Sequence[str], None] = 'fd91b2ece527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('days_of_the_week', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'days_of_the_week')
    # ### end Alembic commands ###
